parameters:
- name: ubuntuVersion
  displayName: Ubuntu Version
  type: string
  default: 1804
  values:
  - 1804
  - 1604
- name: poolType
  displayName: Agents Pool Type
  type: string
  default: BaseSGX
  values:
  - BaseSGX
  - CISGX

jobs:
- job: Ubuntu_${{ parameters.ubuntuVersion }}_Tests
  pool: ${{ parameters.ubuntuVersion }}${{ parameters.poolType }}agentspool
  steps:
  - checkout: self
    submodules: true
    persistCredentials: true

  - task: Bash@3
    displayName: "Install and Run Ansible Playbook"
    inputs:
      targetType: 'inline'
      script: |
          sudo ./install-ansible.sh
          sudo ansible-playbook oe-contributors-acc-setup.yml
      workingDirectory: 'scripts/ansible'

  - task: Bash@3
    displayName: "Build and Test OE SDK"
    inputs:
      targetType: 'inline'
      script: |
          mkdir build && \
          cd build && \
          cmake -G "Ninja" .. && \
          ninja && \
          ctest
