# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: '1604BaseSGXagentspool'

steps:
- checkout: self
  submodules: true
  persistCredentials: true

- task: Bash@3
  displayName: "Install and Run Ansible Playbook"
  inputs:
    targetType: 'inline'
    script: |
        sudo ./install-ansible.sh
        sudo ansible-playbook oe-contributors-acc-setup.yml
    workingDirectory: 'scripts/ansible'

- task: Bash@3
  displayName: "Build and Test OE SDK"
  inputs:
    targetType: 'inline'
    script: |
        mkdir build && \
        cd build && \
        cmake -G "Ninja" .. && \
        ninja && \
        ctest
