# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

---
- hosts: windows-agents
  any_errors_fatal: true
  become_method: runas
  tasks:
    - name: Install Windows Pre-Requisites
      import_tasks: oe-windows-acc-setup-prereqs.yml

    - name: Install Docker
      script: ../install-windows-docker.ps1

    - name: Windows Post Installation
      import_tasks: oe-windows-acc-setup-post-install.yml
