# Copyright (c) Open Enclave SDK contributors.
# Licensed under the MIT License.

name: Build Open Enclave CI Resources
on:
  push:
    branches: [ master ]
    paths:
      - ".jenkins/infrastructure/**"
      - "scripts/install-windows-prereqs.ps1"
      - "scripts/ansible/**"

jobs:
  build-resources:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Build Containers
            job: OpenEnclave-Build-Docker-Images
          - name: Build Images
            job: OpenEnclave-Build-Azure-Managed-Images
    env:
      JENKINS_SERVER_URL: https://oe-jenkins-tf.westeurope.cloudapp.azure.com
      JENKINS_JOB: ${{ matrix.job }}
      JENKINS_JOB_NAME: ${{ matrix.name }}
    steps:
      - name: Checkout Open Enclave SDK
        uses: actions/checkout@v2

      - name: ${{ env.JENKINS_JOB_NAME }}
        run: curl ${{ env.JENKINS_SERVER_URL }}/job/CI-CD_Infrastructure/job/${{ env.JENKINS_JOB }}/buildWithParameters?token=${{ secrets.JENKINS_TOKEN }}&DOCKER_HUB_PUBLIHS=true&TAG_LATEST=true&DOCKER_TAG=${{ github.head_ref }}-${{ github.sha }}&cause=Master+branch+update
